apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${CI_ENVIRONMENT_URL}
  namespace: ${NAMESPACE}
spec:
  rules:
    - host: ${CI_ENVIRONMENT_URL}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ${CI_PROJECT_NAME}-svc
                port:
                  number: 8080
