apiVersion: v1
kind: ServiceAccount
metadata:
  name: concise-aks
  namespace: ${NAMESPACE}
  labels:
    app: ${IMAGE_NAME}
    environment: ${CI_ENVIRONMENT_NAME}
    servicecode: ${CMDB_SERVICE_CODE}
    projectID: "${CI_PROJECT_ID}"
    pipelineID: "${CI_PIPELINE_ID}"
automountServiceAccountToken: false
imagePullSecrets:
  - name: ${APP}
